### ISSUE TITLE
Display bug on the '/secondfactor' page, using Safari

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#199]
Hi,

As you can see below (bottom left corner), there is some display bug on the Authelia's `/secondfactor` page, when using Safari—both desktop and mobile versions are affected. Other pages are properly rendered.
I had not noticed such an issue in earlier versions of Authelia.

This bug does not affect Chrome—I have not tested with Firefox, Opera, Edge or Internet Explorer.

<img width="1440" alt="screen shot 2017-11-02 at 10 53 38 pm" src="https://user-images.githubusercontent.com/14371127/32359118-a239a81a-c021-11e7-9acc-1944d0ea82d6.png">

**Comment by n4kre** [comment]
This explain the rationale behind it:
<img width="1440" alt="screen shot 2017-11-02 at 11 36 24 pm" src="https://user-images.githubusercontent.com/14371127/32359786-bf4acc9a-c026-11e7-8397-228d011384b4.png">
I guess the branch `bugfix/firefox-u2f-api` will fix it. I will try once code is available on the master.

**Comment by clems4ever** [comment]
Hello @n4kre, this is exactly the same bug I had with Firefox yesterday. It should be fixed with the ongoing PR indeed :).

**Comment by jmccoy555** [comment]
Morning,

I was also seeing this with beta build of Firefox 57.0b13 which is that is due to support U2F keys natively, (was waiting for the release version to report). 
 
bugfix/firefox-u2f-api has removed the box.

Enabiling the u2f in about:config with security.webauth.u2f;true and security.webauth.webauthn_enable_usbtoken;true the key now flashed, but when touched it appears accepted i.e. stops flashing, but you do not get past the 2nd factor page. 

Last entry in Authelia's log message

 method='GET', path='/api/u2f/sign_request' requestId='' sessionId='' ip='' message='AuthenticationRequest = [object Object]'


Tested at https://demo.yubico.com/u2f and Firefox its working.

**Comment by n4kre** [comment]
Hi all,

I still have the exact same bug even with the latest version of Authelia.
Am I missing something?

**Comment by jmccoy555** [comment]
Hi @n4kre 

With Firefox 56 I still see the box. With the latest version still in Beta the box is gone, but I can not sign in.

**Comment by clems4ever** [comment]
Hmmm, I will check which version of Firefox I have at home but it was working on my side yesterday. I tested with Chrome and Firefox (with the U2F extension enabled)

I'm using the JS api provided by Yubico to handle the client side of U2F. I'm not even sure the API is compatible with every browser. The best way to test it is to try a registration and authentication at https://demo.yubico.com/u2f and see if it works. If it does, then it might be a bug in Authelia.

**Comment by clems4ever** [comment]
You can help by providing a matrix with all tested browsers (with their version and wether they use an external plugin) and whether they work with the Yubico demo. The matrix should be the same for Authelia. If it is not, I need to fix this.

**Comment by n4kre** [comment]
I may be totally wrong, but is it normal that there are still references to the Google U2F module in [u2f-api.js](https://github.com/clems4ever/authelia/blob/master/client/src/thirdparties/u2f-api.js)? I simply have *<kbd>CTRL</kbd>+<kbd>F</kbd>ed* `chrome-extension://`. That might explain why the *iframe* is not loading on other web browsers.

**Comment by clems4ever** [comment]
Well, this constant is in the U2F API provided by Yubico. I don't know what it is supposed to do while executed in firefox for example but it seems to work anyway...

**Comment by n4kre** [comment]
Hi @clems4ever,

Using Firefox 57.0 on macOS, Authelia won't unfortunately work with my YubiKey 4.
The **iframe* is not visible anymore and I have no error in Firefox console. However, although the YubiKey starts blinking when Authelia asks to validate the second factor, it just stops blinking when I touch it… and that's all: nothing else happens. I cannot find any information about what is actually happening then: neither in Firefox logs, nor in Authelia logs.

Here is how I have configured Firefox to support U2F (does work on Yubico U2F test web page).

<img width="820" alt="screen shot 2017-11-23 at 10 06 37 am" src="https://user-images.githubusercontent.com/14371127/33179253-c1ff38b6-d036-11e7-8da2-cf2b6f48f03a.png">

**Comment by n4kre** [comment]
Oh, I have this error in Firefox console:

<img width="736" alt="screen shot 2017-11-23 at 10 20 08 am" src="https://user-images.githubusercontent.com/14371127/33179637-24840da8-d038-11e7-961b-9e0d270c7003.png">

**Comment by clems4ever** [comment]
Hello @n4kre , do you have the U2F plugin installed?

**Comment by n4kre** [comment]
Hi @clems4ever,

It's been a while!

What kind of plugin are you talking about? Isn't it native in Firefox Quantum?

**Comment by clems4ever** [comment]
Since you proposed a solution that works on firefox, I will add it in the documentation and close this thread once done.

**Comment by clems4ever** [comment]
I created this wiki page: https://github.com/clems4ever/authelia/wiki/Browser-support-for-U2F.
