### ISSUE TITLE
U2F is not working under Firefox 62

### ISSUE THREAD

**Issue by SilverBut** [clems4ever/authelia#277]
The U2F key is not working under Firefox 62. When the 2FA page loaded, the hint of asking for U2F key is shown by Firefox, and the key is blinking. However, when touched the key, nothing will happen.

The following error is found in the console after the page is loaded:

```
 TypeError: setting getter-only property "u2f" u2f-api.js:17:5
	<Anonymous> https://login.example.com/js/u2f-api.js:17:5
```

**Comment by clems4ever** [comment]
Hello @SilverBut , thank you for reporting. I'll give a try to that https://github.com/mastahyeti/u2f-api.

**Comment by b71729** [comment]
I'm experiencing the same with Firefox 62.0; Github u2f works fine.
Support for u2f is opted-in via config `security.webauth.u2f=true`

**Comment by clems4ever** [comment]
Hello @b71729 , thank you for the trick. @SilverBut , can you try it out?

**Comment by SilverBut** [comment]
Hi. Thanks for providing the information. However this option must be set to TRUE. My previous report is also based on setting this to TRUE. 

Actually, Firefox won't support hardware U2F keys unless you set this to TRUE.

**Comment by clems4ever** [comment]
Thank you @n4kre  for the screenshots.

**Comment by clems4ever** [comment]
Should be fixed after #292 is merged.

**Comment by n4kre** [comment]
Still not working for me – although it's fine on https://demo.yubico.com/u2f … :/

<img width="1280" alt="screen shot 2018-10-28 at 12 41 47 am" src="https://user-images.githubusercontent.com/14371127/47609999-ca397b80-da4a-11e8-96f9-d93a1ca5a511.png">
<img width="1280" alt="screen shot 2018-10-28 at 12 41 26 am" src="https://user-images.githubusercontent.com/14371127/47610000-d1f92000-da4a-11e8-9a6f-e2f3a6945e85.png">

**Comment by clems4ever** [comment]
I also had this warning but it's not directly related to your issue. Can you try in an incognito window to make sure it's not a caching issue?

**Comment by n4kre** [comment]
For some reason, my U2F token had been unregistered ("Reply with error 200: No U2F registration found") – how can this even happen?

I re-enrolled, and know everything works perfectly! Thank you for fixing the issue :)

**Comment by clems4ever** [comment]
Great, I will close the issue and re-open it if someone still have problems. Thanks for your feedback.

**Comment by SilverBut** [comment]
Fix confirmed, and now works under latest Firefox. Thanks!

**Comment by SilverBut** [comment]
@clems4ever 
Strange. Now Chromium 70 on Linux can not use U2F keys...
I am trying to figure out why. Is there any configurations I should set to Chrome to enable U2F?

**Comment by clems4ever** [comment]
Hello @SilverBut , not it should be working without any configuration. Or I'm not aware of it...

**Comment by SilverBut** [comment]
More strange...
I'm using docker image `clems4ever/authelia:master`. Both Chrome 70.0.3538.67 on WIndows and Chromium on Linux did not recognized my Yubikey. Console reported nothing.

**Comment by SilverBut** [comment]
Gotcha. @clems4ever 
In `authelia.js`:
```js
            function u2fApiSign(appId, challenge, registeredKey, timeout) {
                return new BluebirdPromise(function(resolve, reject) {
                    window.u2f.sign(appId, challenge, [registeredKey], function(signResponse) {
                        if (signResponse.errorCode != 0) {
                            reject(new Error(signResponse.errorMessage));
                            return;
                        }
```
I don't know where it comes from since I know nothing about npm and how JS package managers combine files, so you may can search it for yourself. However I know that Chrome/Chromium does not have a object named `window.u2f`. Only firefox has it, and as you have said before, an option needs to be enabled in the settings.

And according to [this line](https://github.com/mastahyeti/u2f-api/blob/master/u2f-api-polyfill.js#L30) it should exists `window.u2f` under chrome. However I can not find it. Actually I can not even find any text like that in neither `authelia.js` nor the original HTML.

**Comment by clems4ever** [comment]
@SilverBut , thank you for the analysis. I indeed figured out that I broke U2F. My bad... I did a patch and I will push it right now.

**Comment by clems4ever** [comment]
@SilverBut , here you go https://github.com/clems4ever/authelia/pull/300.

**Comment by clems4ever** [comment]
Should be ok now, I tested it on my setup. @SilverBut , please let me know.

**Comment by SilverBut** [comment]
@clems4ever Seems not. My instance is running behind a Cloudflare CDN, and after I clicked the blinking LED on the key, console told me:
```
authelia.js:19748 XHR finished loading: GET "https://EXAMPLE.org/api/u2f/sign_request".
send @ authelia.js:19748
ajax @ authelia.js:19354
jQuery.(anonymous function) @ authelia.js:19503
BluebirdPromise @ authelia.js:40
Promise._execute @ authelia.js:1549
Promise._resolveFromExecutor @ authelia.js:3827
Promise @ authelia.js:3423
default_1 @ authelia.js:39
startU2fAuthentication @ authelia.js:391
validate @ authelia.js:401
(anonymous) @ authelia.js:457
mightThrow @ authelia.js:13682
process @ authelia.js:13750
setTimeout (async)
(anonymous) @ authelia.js:13788
fire @ authelia.js:13416
fireWith @ authelia.js:13546
fire @ authelia.js:13554
fire @ authelia.js:13416
fireWith @ authelia.js:13546
ready @ authelia.js:14026
completed @ authelia.js:14036
authelia.js:19748 POST https://EXAMPLE.org/api/u2f/sign net::ERR_SPDY_PROTOCOL_ERROR 200
send @ authelia.js:19748
ajax @ authelia.js:19354
(anonymous) @ authelia.js:372
Promise._execute @ authelia.js:1549
Promise._resolveFromExecutor @ authelia.js:3827
Promise @ authelia.js:3423
finishU2fAuthentication @ authelia.js:371
(anonymous) @ authelia.js:397
tryCatcher @ authelia.js:5834
Promise._settlePromiseFromHandler @ authelia.js:3856
Promise._settlePromise @ authelia.js:3913
Promise._settlePromise0 @ authelia.js:3958
Promise._settlePromises @ authelia.js:4037
(anonymous) @ authelia.js:756
Promise.then (async)
schedule @ authelia.js:5062
Async.settlePromises @ authelia.js:755
Promise._fulfill @ authelia.js:3984
Promise._resolveCallback @ authelia.js:3776
resolve @ authelia.js:5480
Promise.then (async)
tryCatcher @ authelia.js:5834
doThenable @ authelia.js:5470
tryConvertToPromise @ authelia.js:5435
Promise._resolveCallback @ authelia.js:3775
Promise._settlePromiseFromHandler @ authelia.js:3868
Promise._settlePromise @ authelia.js:3913
Promise._settlePromise0 @ authelia.js:3958
Promise._settlePromises @ authelia.js:4037
(anonymous) @ authelia.js:756
Promise.then (async)
schedule @ authelia.js:5062
Async.settlePromises @ authelia.js:755
Promise._fulfill @ authelia.js:3984
Promise._resolveCallback @ authelia.js:3776
(anonymous) @ authelia.js:3828
$.get.done @ authelia.js:42
fire @ authelia.js:13416
fireWith @ authelia.js:13546
done @ authelia.js:19453
(anonymous) @ authelia.js:19696
load (async)
send @ authelia.js:19715
ajax @ authelia.js:19354
jQuery.(anonymous function) @ authelia.js:19503
BluebirdPromise @ authelia.js:40
Promise._execute @ authelia.js:1549
Promise._resolveFromExecutor @ authelia.js:3827
Promise @ authelia.js:3423
default_1 @ authelia.js:39
startU2fAuthentication @ authelia.js:391
validate @ authelia.js:401
(anonymous) @ authelia.js:457
mightThrow @ authelia.js:13682
process @ authelia.js:13750
setTimeout (async)
(anonymous) @ authelia.js:13788
fire @ authelia.js:13416
fireWith @ authelia.js:13546
fire @ authelia.js:13554
fire @ authelia.js:13416
fireWith @ authelia.js:13546
ready @ authelia.js:14026
completed @ authelia.js:14036
authelia.js:19748 XHR failed loading: POST "https://EXAMPLE.org/api/u2f/sign".

**Comment by clems4ever** [comment]
Hello @SilverBut , was your setup working with previous version of the u2f library?

**Comment by SilverBut** [comment]
I think it works but not 100% sure. At least works under Chrome.

**Comment by clems4ever** [comment]
@SilverBut, it works or worked?
@n4kre , can you please test on your side to see if you have troubles with either Chrome or Firefox? I'd like to confirm my fix is ok on other devices than mine since U2F is hard to test in Travis.

**Comment by clems4ever** [comment]
I retested again to be sure and indeed something was broken. I made an additional PR to fix it: https://github.com/clems4ever/authelia/pull/301.

**Comment by n4kre** [comment]
@clems4ever, thank you for fixing it: I confirm https://github.com/clems4ever/authelia/pull/301/commits/8c175c8d1104114b3f771ca5f9cc84a4ede25d95 solved the issue in Firefox 👍

**Comment by SilverBut** [comment]
@clems4ever Still not working and still having logs in [this reply](https://github.com/clems4ever/authelia/issues/277#issuecomment-436554359). Do you PR already contained in `clems4ever/authelia:master`?

**Comment by SilverBut** [comment]
I think I found something interestring.

In line 370 of `authelia.js`:
```js
function finishU2fAuthentication(responseData, $) {
    return new BluebirdPromise(function (resolve, reject) {
        $.ajax({
            url: Endpoints.SECOND_FACTOR_U2F_SIGN_POST,
            data: responseData,
            method: "POST",
            dataType: "json"
        })
            .done(function (body) {
            if (body && "error" in body) {
                reject(new Error(body.error));
                return;
            }
            resolve(body.redirect);
        })
            .fail(function (xhr, textStatus) {
            reject(new Error(textStatus));
        });
    });
}
```

The data is sent in `json`, and `responseData`:
```
> typeof(responseData)
"object"
```
 However if you follow the ajax and check it in Network panel you will see the request format is in something like `x-www-form-urlencoded`. Here is the request, copied in `curl` format:
```json
curl 'https://EXAMPLE.org/api/u2f/sign'\
 -H 'origin: https://EXAMPLE.org'\
 -H 'accept-encoding: gzip, deflate, br'\
 -H 'accept-language: en-US,en;q=0.9'\
 -H 'x-requested-with: XMLHttpRequest'\
 -H 'cookie: __cfduid=EXAMPLE; authelia_session=EXAMPLE'\
 -H 'pragma: no-cache'\
 -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36'\
 -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8'\
 -H 'accept: application/json, text/javascript, */*; q=0.01'\
 -H 'cache-control: no-cache'\
 -H 'authority: EXAMPLE.org'\
 -H 'referer: https://EXAMPLE.org/secondfactor' \
 --data 'keyHandle=EXAMPLE&clientData=EXAMPLE&signatureData=EXAMPLE' --compressed
```

**Comment by clems4ever** [comment]
No it's not in the latest Docker image. I'll fix the test in my PR and make it merged so that it is included in latest Docker image for you to test.

**Comment by clems4ever** [comment]
It should now be fixed in v3.10.0. Please check and re-open the issue if you're still having troubles with U2F on Chrome or Firefox.

**Comment by SilverBut** [comment]
After test on several version of chrome, yes it works. Thanks @clems4ever !
